import { AlertCircle, BadgeCheck, CalendarDays, ClipboardList, Copy, History, KeyRound, Plus, Settings, ShieldCheck, UserPlus, Users, X } from "lucide-react";
import { ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { ApiError, apiGet, apiPatch, apiPost, apiPut } from "../../lib/api";
import type { Role } from "../types";
import { useDialogFocusTrap, WorkspacePage } from "./RecordViews";
import { useContextualActions } from "./SidebarActions";
import "./administration.css";

type Branch = { id: string; code: string; name: string; city: string | null; timezone: string | null; weeklyCapacityHours: number };
type Member = { id: string; name: string; email: string; role: Role; isActive: boolean; branchId: string | null; branchName: string | null; branchAccess: Array<{ id: string; name: string; code: string }> };
type Invitation = { id: string; displayName: string; email: string; role: Role; status: string; branchId: string | null; expiresAt: string };
type Schedule = { id: string; userId: string; userName: string; branchName: string; startsAt: string; endsAt: string; status: string; note: string | null };
type Workload = { id: string; userId: string; userName: string; branchName: string | null; title: string; status: string; priority: string; dueAt: string | null };
type AuditEvent = { id: string; actorName: string | null; actorRole: string | null; action: string; statusCode: number; targetType: string | null; targetId: string | null; requestId: string | null; occurredAt: string };
type RolePreset = { role: Role; capabilities: string[] };
type AdminData = { members: Member[]; branches: Branch[]; invitations: Invitation[]; schedules: Schedule[]; workloads: Workload[]; auditEvents: AuditEvent[]; roles: RolePreset[]; settings: { name: string; timezone: string; locale: string; currency: string; weekStartsOn: number } };
type Tab = "people" | "access" | "schedules" | "workloads" | "audit" | "settings";

const ROLE_LABELS: Record<Role, string> = { admin: "Admin", general_manager: "General manager", sales_manager: "Sales manager", bdc_rep: "BDC representative", finance_manager: "Finance manager", service_advisor: "Service advisor", receptionist: "Receptionist" };
const TABS: Array<{ id: Tab; label: string; icon: typeof Users }> = [
  { id: "people", label: "People & invitations", icon: Users }, { id: "access", label: "Roles & access", icon: KeyRound },
  { id: "schedules", label: "Schedules", icon: CalendarDays }, { id: "workloads", label: "Workloads", icon: ClipboardList },
  { id: "audit", label: "Audit history", icon: History }, { id: "settings", label: "Settings", icon: Settings },
];

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not set"; }
function errorMessage(cause: unknown) { return cause instanceof ApiError ? `${cause.message}${cause.requestId ? ` Request ${cause.requestId}.` : ""}` : "The request could not be completed."; }

function AdminDialog({ title, description, onClose, children }: { title: string; description: string; onClose: () => void; children: ReactNode }) {
  const ref = useRef<HTMLElement>(null); const titleId = useMemo(() => `admin-dialog-${title.toLowerCase().replace(/[^a-z]+/g, "-")}`, [title]);
  useDialogFocusTrap(ref, onClose);
  return <div className="modal-scrim admin-dialog-scrim" role="presentation" onMouseDown={(event) => event.currentTarget === event.target && onClose()}>
    <section ref={ref} tabIndex={-1} className="admin-dialog" role="dialog" aria-modal="true" aria-labelledby={titleId}>
      <header><div><h2 id={titleId}>{title}</h2><p>{description}</p></div><button type="button" onClick={onClose} aria-label={`Close ${title}`}><X /></button></header>{children}
    </section></div>;
}

export function Administration() {
  const [data, setData] = useState<AdminData | null>(null); const [tab, setTab] = useState<Tab>("people");
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [dialog, setDialog] = useState<"invite" | "schedule" | "workload" | "access" | null>(null);
  const [selectedMember, setSelectedMember] = useState<Member | null>(null);

  async function load() { setError(""); try { setData(await apiGet<AdminData>("/api/v1/administration")); } catch (cause) { setError(errorMessage(cause)); } }
  useEffect(() => { void load(); }, []);
  useContextualActions(() => [{ id: "invite-member", label: "Invite member", icon: UserPlus, onClick: () => setDialog("invite") }, { id: "create-schedule", label: "Create schedule", icon: CalendarDays, onClick: () => setDialog("schedule") }, { id: "assign-work", label: "Assign workload", icon: ClipboardList, onClick: () => setDialog("workload") }], []);

  async function mutate(action: () => Promise<unknown>, success: string) { setError(""); try { await action(); setDialog(null); setNotice(success); await load(); } catch (cause) { setError(errorMessage(cause)); } }
  async function copy(label: string, value: string) { try { await navigator.clipboard.writeText(value); setNotice(`${label} copied.`); } catch { setError(`${label} could not be copied. Select the value and copy it manually.`); } }

  return <WorkspacePage><div className="administration-workspace">
    <section className="admin-hero"><div><span>Account & settings</span><h1>Administration</h1><p>Manage people, access, capacity, and governance across the connected dealership.</p></div>
      <div className="admin-hero-metrics"><div><strong>{data?.members.filter((m) => m.isActive).length ?? "—"}</strong><span>Active members</span></div><div><strong>{data?.invitations.filter((i) => i.status === "pending").length ?? "—"}</strong><span>Pending invites</span></div><div><strong>{data?.workloads.length ?? "—"}</strong><span>Open work items</span></div></div></section>
    {error && <p className="admin-message admin-message--error" role="alert"><AlertCircle />{error}<button type="button" onClick={() => void load()}>Retry</button></p>}
    {notice && <p className="admin-message admin-message--success" role="status"><BadgeCheck />{notice}<button type="button" onClick={() => setNotice("")} aria-label="Dismiss notification"><X /></button></p>}
    <div className="admin-tabs" role="tablist" aria-label="Administration sections">{TABS.map((item) => <button key={item.id} type="button" role="tab" aria-selected={tab === item.id} aria-controls={`admin-panel-${item.id}`} id={`admin-tab-${item.id}`} onClick={() => setTab(item.id)}><item.icon />{item.label}</button>)}</div>
    {!data && !error && <div className="admin-state" role="status">Loading administration records…</div>}
    {data && <section id={`admin-panel-${tab}`} role="tabpanel" aria-labelledby={`admin-tab-${tab}`}>
      {tab === "people" && <PeoplePanel data={data} onInvite={() => setDialog("invite")} onAccess={(member) => { setSelectedMember(member); setDialog("access"); }} onMutate={mutate} onCopy={copy} />}
      {tab === "access" && <AccessPanel roles={data.roles} members={data.members} onAccess={(member) => { setSelectedMember(member); setDialog("access"); }} />}
      {tab === "schedules" && <SchedulesPanel schedules={data.schedules} onCreate={() => setDialog("schedule")} onMutate={mutate} />}
      {tab === "workloads" && <WorkloadsPanel workloads={data.workloads} onCreate={() => setDialog("workload")} onMutate={mutate} />}
      {tab === "audit" && <AuditPanel events={data.auditEvents} onCopy={copy} />}
      {tab === "settings" && <SettingsPanel data={data} onMutate={mutate} />}
    </section>}
    {dialog === "invite" && data && <InviteDialog branches={data.branches} roles={data.roles} onClose={() => setDialog(null)} onSubmit={(body) => mutate(() => apiPost("/api/v1/administration/invitations", body), "Invitation created. Share it through your approved identity workflow.")} />}
    {dialog === "schedule" && data && <ScheduleDialog data={data} onClose={() => setDialog(null)} onSubmit={(body) => mutate(() => apiPost("/api/v1/administration/schedules", body), "Schedule saved.")} />}
    {dialog === "workload" && data && <WorkloadDialog data={data} onClose={() => setDialog(null)} onSubmit={(body) => mutate(() => apiPost("/api/v1/administration/workloads", body), "Workload assigned.")} />}
    {dialog === "access" && data && selectedMember && <AccessDialog member={selectedMember} branches={data.branches} onClose={() => setDialog(null)} onSubmit={(branchIds) => mutate(() => apiPut(`/api/v1/administration/members/${selectedMember.id}/branch-access`, { branchIds }), "Branch access updated.")} />}
  </div></WorkspacePage>;
}

function Card({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <section className="admin-card"><header><h2>{title}</h2>{action}</header>{children}</section>; }
function Empty({ children }: { children: ReactNode }) { return <p className="admin-empty">{children}</p>; }

function PeoplePanel({ data, onInvite, onAccess, onMutate, onCopy }: { data: AdminData; onInvite: () => void; onAccess: (m: Member) => void; onMutate: (a: () => Promise<unknown>, s: string) => void; onCopy: (l: string, v: string) => void }) {
  return <div className="admin-grid"><Card title="Members" action={<button className="admin-primary" type="button" onClick={onInvite}><UserPlus />Invite member</button>}><div className="admin-table-wrap" role="region" aria-label="Members table" tabIndex={0}><table><thead><tr><th>Member</th><th>Role</th><th>Branch access</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.members.map((m) => <tr key={m.id}><td><strong>{m.name}</strong><span>{m.email}</span></td><td>{ROLE_LABELS[m.role]}</td><td>{m.branchAccess.length ? m.branchAccess.map((b) => b.code).join(", ") : m.branchName ?? "All branches"}</td><td><span className={`admin-status admin-status--${m.isActive ? "active" : "inactive"}`}>{m.isActive ? "Active" : "Deactivated"}</span></td><td><div className="admin-row-actions"><button type="button" onClick={() => onCopy("Member email", m.email)}><Copy />Copy email</button><button type="button" onClick={() => onAccess(m)}>Edit access</button><button type="button" onClick={() => onMutate(() => apiPatch(`/api/v1/users/${m.id}`, { isActive: !m.isActive }), m.isActive ? "Member deactivated." : "Member reactivated.")}>{m.isActive ? "Deactivate" : "Reactivate"}</button></div></td></tr>)}</tbody></table></div></Card>
    <Card title="Invitations"><div className="admin-list">{data.invitations.length === 0 && <Empty>No invitations yet.</Empty>}{data.invitations.map((i) => <article key={i.id}><div><strong>{i.displayName}</strong><span>{i.email} · {ROLE_LABELS[i.role]}</span></div><div><span className={`admin-status admin-status--${i.status}`}>{i.status}</span>{i.status === "pending" && <button type="button" onClick={() => onMutate(() => apiPatch(`/api/v1/administration/invitations/${i.id}`, { status: "revoked" }), "Invitation revoked.")}>Revoke</button>}</div></article>)}</div></Card></div>;
}

function AccessPanel({ roles, members, onAccess }: { roles: RolePreset[]; members: Member[]; onAccess: (m: Member) => void }) { return <div className="admin-grid"><Card title="Role permission presets"><div className="admin-role-grid">{roles.map((r) => <article key={r.role}><ShieldCheck /><h3>{ROLE_LABELS[r.role]}</h3><p>{r.capabilities.length} capabilities</p><ul>{r.capabilities.map((c) => <li key={c}>{c}</li>)}</ul></article>)}</div></Card><Card title="Branch access"><div className="admin-list">{members.map((m) => <article key={m.id}><div><strong>{m.name}</strong><span>{m.branchAccess.length ? m.branchAccess.map((b) => b.name).join(", ") : m.branchName ?? "All branches"}</span></div><button type="button" onClick={() => onAccess(m)}>Edit branch access</button></article>)}</div></Card></div>; }
function SchedulesPanel({ schedules, onCreate, onMutate }: { schedules: Schedule[]; onCreate: () => void; onMutate: (a: () => Promise<unknown>, s: string) => void }) { return <Card title="Team schedule" action={<button className="admin-primary" type="button" onClick={onCreate}><Plus />Create schedule</button>}><div className="admin-list">{schedules.length === 0 && <Empty>No upcoming schedules.</Empty>}{schedules.map((s) => <article key={s.id}><div><strong>{s.userName} · {s.branchName}</strong><span>{formatDate(s.startsAt)} – {formatDate(s.endsAt)}{s.note ? ` · ${s.note}` : ""}</span></div><div><span className={`admin-status admin-status--${s.status}`}>{s.status}</span>{s.status !== "cancelled" && <button type="button" onClick={() => onMutate(() => apiPatch(`/api/v1/administration/schedules/${s.id}`, { status: "cancelled" }), "Schedule cancelled.")}>Cancel schedule</button>}</div></article>)}</div></Card>; }
function WorkloadsPanel({ workloads, onCreate, onMutate }: { workloads: Workload[]; onCreate: () => void; onMutate: (a: () => Promise<unknown>, s: string) => void }) { return <Card title="Open workloads" action={<button className="admin-primary" type="button" onClick={onCreate}><Plus />Assign work</button>}><div className="admin-list">{workloads.length === 0 && <Empty>No open workload assignments.</Empty>}{workloads.map((w) => <article key={w.id}><div><strong>{w.title}</strong><span>{w.userName}{w.branchName ? ` · ${w.branchName}` : ""} · {w.priority} priority · due {formatDate(w.dueAt)}</span></div><select aria-label={`Status for ${w.title}`} value={w.status} onChange={(e) => onMutate(() => apiPatch(`/api/v1/administration/workloads/${w.id}`, { status: e.target.value }), "Workload status updated.")}>{["queued", "in_progress", "blocked", "completed"].map((s) => <option key={s} value={s}>{s.replace("_", " ")}</option>)}</select></article>)}</div></Card>; }
function AuditPanel({ events, onCopy }: { events: AuditEvent[]; onCopy: (l: string, v: string) => void }) { return <Card title="Audit history"><div className="admin-table-wrap" role="region" aria-label="Audit history table" tabIndex={0}><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Request</th></tr></thead><tbody>{events.map((e) => <tr key={e.id}><td>{formatDate(e.occurredAt)}</td><td>{e.actorName ?? "System"}<span>{e.actorRole}</span></td><td>{e.action}<span>HTTP {e.statusCode}</span></td><td>{e.targetType ?? "—"}{e.targetId && <button type="button" onClick={() => onCopy("Target ID", e.targetId!)}><Copy />Copy target ID</button>}</td><td>{e.requestId ? <button type="button" onClick={() => onCopy("Request ID", e.requestId!)}><Copy />Copy request ID</button> : "—"}</td></tr>)}</tbody></table></div></Card>; }

function SettingsPanel({ data, onMutate }: { data: AdminData; onMutate: (a: () => Promise<unknown>, s: string) => void }) { const [form, setForm] = useState(data.settings); return <div className="admin-grid"><Card title="Organization settings"><form className="admin-form" onSubmit={(e) => { e.preventDefault(); onMutate(() => apiPatch("/api/v1/administration/settings", form), "Organization settings saved."); }}><label><span>Organization name</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span>Timezone</span><input required value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })} /></label><label><span>Locale</span><input required value={form.locale} onChange={(e) => setForm({ ...form, locale: e.target.value })} /></label><label><span>Currency</span><input required maxLength={3} value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value.toUpperCase() })} /></label><label><span>Week starts on</span><select value={form.weekStartsOn} onChange={(e) => setForm({ ...form, weekStartsOn: Number(e.target.value) })}><option value={0}>Sunday</option><option value={1}>Monday</option></select></label><button className="admin-primary" type="submit">Save organization settings</button></form></Card><Card title="Branch settings"><div className="admin-list">{data.branches.map((b) => <BranchSettings key={b.id} branch={b} onMutate={onMutate} />)}</div></Card></div>; }
function BranchSettings({ branch, onMutate }: { branch: Branch; onMutate: (a: () => Promise<unknown>, s: string) => void }) { const [timezone, setTimezone] = useState(branch.timezone ?? ""); const [capacity, setCapacity] = useState(branch.weeklyCapacityHours); return <form className="admin-branch-settings" onSubmit={(e) => { e.preventDefault(); onMutate(() => apiPatch(`/api/v1/administration/branches/${branch.id}/settings`, { timezone, weeklyCapacityHours: capacity }), `${branch.name} settings saved.`); }}><div><strong>{branch.name}</strong><span>{branch.code} · {branch.city ?? "City not set"}</span></div><label><span>Timezone</span><input value={timezone} onChange={(e) => setTimezone(e.target.value)} /></label><label><span>Weekly capacity hours</span><input type="number" min={0} value={capacity} onChange={(e) => setCapacity(Number(e.target.value))} /></label><button type="submit">Save branch</button></form>; }

function InviteDialog({ branches, roles, onClose, onSubmit }: { branches: Branch[]; roles: RolePreset[]; onClose: () => void; onSubmit: (b: object) => void }) { const [f, setF] = useState({ displayName: "", email: "", role: "receptionist" as Role, branchId: "" }); return <AdminDialog title="Invite member" description="Create a time-limited invitation record for your approved identity workflow." onClose={onClose}><form className="admin-form" onSubmit={(e) => { e.preventDefault(); onSubmit({ ...f, branchId: f.branchId || null }); }}><label><span>Full name</span><input autoFocus required value={f.displayName} onChange={(e) => setF({ ...f, displayName: e.target.value })} /></label><label><span>Work email</span><input required type="email" value={f.email} onChange={(e) => setF({ ...f, email: e.target.value })} /></label><label><span>Role preset</span><select value={f.role} onChange={(e) => setF({ ...f, role: e.target.value as Role })}>{roles.map((r) => <option key={r.role} value={r.role}>{ROLE_LABELS[r.role]}</option>)}</select></label><label><span>Home branch</span><select value={f.branchId} onChange={(e) => setF({ ...f, branchId: e.target.value })}><option value="">All branches</option>{branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="admin-form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="admin-primary" type="submit">Create invitation</button></div></form></AdminDialog>; }
function ScheduleDialog({ data, onClose, onSubmit }: { data: AdminData; onClose: () => void; onSubmit: (b: object) => void }) { const [f, setF] = useState({ userId: data.members[0]?.id ?? "", branchId: data.branches[0]?.id ?? "", startsAt: "", endsAt: "", status: "scheduled", note: "" }); return <AdminDialog title="Create schedule" description="Schedule a member at a branch with a clear start, end, and status." onClose={onClose}><form className="admin-form" onSubmit={(e) => { e.preventDefault(); onSubmit(f); }}><label><span>Member</span><select required value={f.userId} onChange={(e) => setF({ ...f, userId: e.target.value })}>{data.members.filter((m) => m.isActive).map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label><span>Branch</span><select required value={f.branchId} onChange={(e) => setF({ ...f, branchId: e.target.value })}>{data.branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label><span>Starts</span><input required type="datetime-local" value={f.startsAt} onChange={(e) => setF({ ...f, startsAt: e.target.value })} /></label><label><span>Ends</span><input required type="datetime-local" value={f.endsAt} onChange={(e) => setF({ ...f, endsAt: e.target.value })} /></label><label className="admin-form-full"><span>Note</span><textarea value={f.note} onChange={(e) => setF({ ...f, note: e.target.value })} /></label><div className="admin-form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="admin-primary" type="submit">Save schedule</button></div></form></AdminDialog>; }
function WorkloadDialog({ data, onClose, onSubmit }: { data: AdminData; onClose: () => void; onSubmit: (b: object) => void }) { const [f, setF] = useState({ userId: data.members[0]?.id ?? "", branchId: "", title: "", priority: "normal", dueAt: "" }); return <AdminDialog title="Assign workload" description="Assign accountable operational work without creating a disconnected employee record." onClose={onClose}><form className="admin-form" onSubmit={(e) => { e.preventDefault(); onSubmit({ ...f, branchId: f.branchId || null, dueAt: f.dueAt || null }); }}><label><span>Member</span><select required value={f.userId} onChange={(e) => setF({ ...f, userId: e.target.value })}>{data.members.filter((m) => m.isActive).map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label><span>Branch</span><select value={f.branchId} onChange={(e) => setF({ ...f, branchId: e.target.value })}><option value="">Organization-wide</option>{data.branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="admin-form-full"><span>Work item</span><input autoFocus required value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} /></label><label><span>Priority</span><select value={f.priority} onChange={(e) => setF({ ...f, priority: e.target.value })}>{["low", "normal", "high", "urgent"].map((p) => <option key={p}>{p}</option>)}</select></label><label><span>Due</span><input type="datetime-local" value={f.dueAt} onChange={(e) => setF({ ...f, dueAt: e.target.value })} /></label><div className="admin-form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="admin-primary" type="submit">Assign work</button></div></form></AdminDialog>; }
function AccessDialog({ member, branches, onClose, onSubmit }: { member: Member; branches: Branch[]; onClose: () => void; onSubmit: (ids: string[]) => void }) { const [ids, setIds] = useState(member.branchAccess.map((b) => b.id)); return <AdminDialog title="Edit branch access" description={`Choose the branches ${member.name} can access.`} onClose={onClose}><form className="admin-form" onSubmit={(e) => { e.preventDefault(); onSubmit(ids); }}><fieldset className="admin-check-list"><legend>Allowed branches</legend>{branches.map((b) => <label key={b.id}><input type="checkbox" checked={ids.includes(b.id)} onChange={(e) => setIds(e.target.checked ? [...ids, b.id] : ids.filter((id) => id !== b.id))} /><span>{b.name} ({b.code})</span></label>)}</fieldset><div className="admin-form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="admin-primary" type="submit">Save branch access</button></div></form></AdminDialog>; }
